#!/bin/bash

# Push Additional Version If Master Branch
if [ "${SOURCE_BRANCH}" = "master" ]
then
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${SOURCE_COMMIT}"
    docker push "${DOCKER_REPO}:${SOURCE_COMMIT}"
fi
