#!/bin/bash

# Push Additional Version If Master Branch
if [ "${SOURCE_BRANCH}" = "main" ]
then
    VERSION=$(date +%Y%m%d%H%M) ; export VERSION
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${VERSION}"
    docker push "${DOCKER_REPO}:${VERSION}"
fi
